apiVersion: v1
kind: Namespace
metadata:
  name: ebpf-debug
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-testing-debug
  namespace: ebpf-debug
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-testing-debug
  namespace: ebpf-debug
  labels:
    app: ebpf-testing-debug
spec:
  selector:
    matchLabels:
      app: ebpf-testing-debug
  template:
    metadata:
      labels:
        app: ebpf-testing-debug
    spec:
      serviceAccountName: ebpf-testing-debug
      hostNetwork: true
      hostPID: true
      containers:
      - name: agent
        image: ebpf-testing:debug
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - BPF
            - NET_ADMIN
            - SYS_RESOURCE
        ports:
        - name: delve
          containerPort: 2345
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ebpf-testing-debug
  namespace: ebpf-debug
  labels:
    app: ebpf-testing-debug
spec:
  type: NodePort
  ports:
  - name: delve
    port: 2345
    targetPort: 2345
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ebpf-testing-debug
